"""Subclass of MainFrameBase, which is generated by wxFormBuilder."""

from FacturaPanel import FacturaPanel
from N_CreditoPanel import N_CreditoPanel
from ClientePanel import ClientePanel
from ProveedorPanel import ProveedorPanel
from ArticuloPanel import ArticuloPanel
from ImportarPanel import ImportarPanel
from ReciboPanel  import ReciboPanel
import LicenciaDialog
import BuscarArticuloDialog
import gui
import wx
import wx.aui
import os



# Implementing MainFrameBase
class MainFrame( gui.MainFrameBase ):
    def __init__( self, parent ):
        gui.MainFrameBase.__init__( self, parent )
    
    # Handlers for MainFrameBase events.   
    def m_mniClientesClick( self, event ):
        self.m_panel = ClientePanel(self.m_auinotebook)
        self.m_auinotebook.AddPage(self.m_panel, " Clientes ", select=True)
        
    def m_mniProveedores( self, event ):
        self.m_panel = ProveedorPanel(self.m_auinotebook)
        self.m_auinotebook.AddPage(self.m_panel, " Proveedores ", select=True)

    def m_mniArticulosClick( self, event ):
        self.m_panel = ArticuloPanel(self.m_auinotebook)
        self.m_auinotebook.AddPage(self.m_panel, " Articulos ", select=True)        
            
    def m_mniImportarClick( self, event ):
        self.m_panel = ImportarPanel(self.m_auinotebook)
        self.m_auinotebook.AddPage(self.m_panel, " Importar ", select=True)        


    def m_mniSalirClick( self, event ):
        self.Close()
    
    def m_mniAcercadeClick( self, event ):
        ing = wx.MessageBox("        Omicron SH \n\nBelgrano 87 - Venado Tuerto \n\nTE (03462) 435614/436614\n\nE-Mail info@omicron-vt.com\n\nWEB www.omicron-vt.com.ar\n\nIntroducir Licencia ?", "Gestion", wx.YES_NO)
        if ing == wx.YES:
            licDialog = LicenciaDialog.LicenciaDialog (self)
            licDialog.ShowModal()
    
    def m_mniFacturaClick( self, event ):
        self.m_panel = FacturaPanel(self.m_auinotebook)
        self.m_auinotebook.AddPage(self.m_panel, " Factura ", select=True)
    def m_mniN_CreditoClick( self, event ):
        self.m_panel = N_CreditoPanel(self.m_auinotebook)
        self.m_auinotebook.AddPage(self.m_panel, " Nota de Credito ", select=True)

    def m_mniCierreZClick( self, event ):
        ok = wx.MessageBox("Emitir Cierre Z ?", "CIERRE Z", wx.OK | wx.CANCEL | wx.ICON_WARNING)        
        if ok == wx.OK:
            os.system("wspooler -p1 -c "+ "9" + chr(28) + "Z")
